# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# TO GENERATE TAILWWIND CSS FILE, RUN THIS COMMAND "npx tailwindcss-cli@latest build -o assets/css/tailwind.css"

title: Carmel By The River
email: stay@carmelrv.com
phone: 1 (831) 624-9329
description: >- # this means to ignore newlines until "baseurl:"
  Your premier destination for RV-ing in the Carmel/Monterey area. Close to all major attractions, so you can go hit the links at Pebble Beach, watch the races at Laguna Seca, lay in the sun on beautiful Carmel Beach, or simply relax in our garden-like setting and enjoy. Join us and create new traditions for years to come.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "carmelrv.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CarmelRV
booking_url: https://bookings.rmscloud.com/Search/Index/2F90DCF2AA65ED8E/90/
permalink: pretty

collections:
  - amenities
  - accommodations
sass:
  style: compressed

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "" 
      type: "pages"
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
